### ISSUE TITLE
Failed to load the language-soy package

### ISSUE THREAD

**Issue by say2joe** [bendman/language-soy#8]
[Enter steps to reproduce below:]

1. Open Atom.io with the package previously installed.
2. View error in red modal at top-right of application window.

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [language-soy](https://github.com/bendman/language-soy) package, v0.1.0

### Stack Trace

Failed to load the language-soy package

```
At Cannot find module './soy-templates-view'

Error: Cannot find module './soy-templates-view'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Users/jjohnson/.atom/packages/language-soy/lib/language-soy.coffee:4:22)
    at Object.<anonymous> (/Users/jjohnson/.atom/packages/language-soy/lib/language-soy.coffee:21:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "projectHome": "/Users/jjohnson/code"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-handlebars, v0.4.0
atom-spotify, v1.2.0
auto-update-packages, v0.2.2
autoclose-html, v0.15.0
color-picker, v1.4.4
docblockr, v0.6.3
language-html, v0.29.0
language-r, v0.1.1
language-soy, v0.1.0
linkify, v0.11.0
linter, v0.12.0
linter-jshint, v0.1.0
linter-jsonlint, v0.1.2
minimap, v4.6.0
open-last-project, v0.3.4
project-manager, v1.15.5
svg-preview, v0.5.1

# Dev
No dev packages
```

**Comment by zenorocha** [comment]
+1

**Comment by rgpower** [comment]
Making the following change to lib/language-soy.coffee fixed it for me:

from:
```javascript
SoyTemplatesView = require ./'soy-templates-view'
```

to:
```javascript
SoyTemplatesView = require 'soy-templates-view'
```

**Comment by bendman** [comment]
@rgpower thanks, I'll take a look at this solution.  Do you want to make a pull request?  If not, I'll should be able to fix it this weekend.

**Comment by rgpower** [comment]
Made pull request (though I admit I have tested it only on OSX Yosemite)

https://github.com/bendman/language-soy/pull/9
